name: Package Push Nuget
on:
  release:
    types: [ created ]

jobs:
  packeg-build:
    name: packeg build and push
    runs-on: ubuntu-latest
    steps:
    - name: git pull
      uses: actions/checkout@v2

    - name: run a one-line script
      run: env

    - name: setting dotnet version 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build --no-restore 

    - name: pack
      run: dotnet pack --include-symbols  -p:PackageVersion=$GITHUB_REF_NAME     

    - name: package push
      run: dotnet nuget push "**/*.symbols.nupkg" -k  ${{secrets.NUGET_TOKEN}}  -s https://api.nuget.org/v3/index.json
        

        